- name: Create local directory to store shared content
  file:
    state: directory
    dest: "{{ shared_docroot }}/{{ shared_domain }}"
    mode: "755"

- name: Copy update-shared script to the server
  template:
    src: templates/update-shared
    dest: /local/systems/update-shared
    mode: "700"

- name: Fetch shared content
  command: /local/systems/update-shared

- name: Create a cron job to run hourly
  cron:
    name: Run update-shared hourly
    special_time: hourly
    job: /local/systems/update-shared

