#!/bin/sh

cd {{ backup_dir }}

# Redirect all output to the backup.log
exec > "/local/systems/backup.log" 2>&1

echo "[$(date)] Starting backup process..."

# Environment Variables
export AWS_ACCESS_KEY_ID="{{ DO_access_key }}"
export AWS_SECRET_ACCESS_KEY="{{ DO_secret_key }}"
export RESTIC_PASSWORD="{{ restic_password }}"


# Compress backup
tar cf -P {{ backup_path }} | bzip2 -9 > {{ backup_name }}.tar.bz2
echo "[$(date)] Compression completed."

# S3 Upload
restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }} backup {{ backup_name }}.tar.bz2
exit_status=$?
echo "restic status: " $exit_status

if [ $exit_status -eq 0 ]; then
  echo "[$(date)] S3 upload completed."

  # Remove local backup data
  rm -rf {{ backup_dir }}/*
  echo "[$(date)] Cleanup completed."
  echo "[$(date)] Backup process finished successfully."

else
  echo "[$(date)] Could not upload data."
fi
